plugins {
    id 'java'
    id 'checkstyle'
}

group = 'com.academy'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

checkstyle {
    toolVersion = '10.21.4'
    configFile = file('config/checkstyle/google_checks.xml')
}

tasks.named('check') {
    dependsOn tasks.named('checkstyleMain')
}

test {
    useJUnitPlatform()
}