plugins {
    id 'java'
    id 'checkstyle'
}

checkstyle {
    toolVersion = '10.15.0'
    configFile = file("config/checkstyle/checkstyle.xml")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(24)
    }
}

group = 'com.academy'
version = '1.0-SNAPSHOT'

jar {
    manifest {
        attributes(
                'Main-Class': 'com.academy.Main'
        )
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.14.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}